name: GitHub Actions Demo # the name of the workflow how it would appear in the Actions tab sidebar
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€ # name on top of the page where github.actor === git username
on: [push] # on what action to run the workflow
jobs:
  Explore-GitHub-Actions: # name of the workflow, displayed above all the executed steps
    runs-on: ubuntu-latest # virtual machine to run on
    steps: # actual steps to execute
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event." # github.event_name === how action was triggered
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!" # os of the actual used virtual machine
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner." # github.repository === git owner/repo
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository # runs ls command on the virtual machine inside the root dir
        run: |
          ls ${{ github.workspace }} 
      - run: echo "ğŸ This job's status is ${{ job.status }}." # in this case prints "ğŸ This job's status is success."
